version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: whoz_es_db
    environment:
      POSTGRES_USER: solid_snake
      POSTGRES_PASSWORD: big_boss
      POSTGRES_DB: whoz_es
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
